'use strict';

// Dev-only routes — never mounted in production
const express      = require('express');
const { getDevCode } = require('../services/otp');

const router = express.Router();

// GET /api/v1/dev/otp?email=...&purpose=signup
// Returns the plaintext OTP stored in memory (generated by createOTP).
// Only works when NODE_ENV !== 'production'.
router.get('/otp', (req, res) => {
  const { email, purpose = 'signup' } = req.query;
  if (!email) return res.status(400).json({ error: 'email required' });
  const code = getDevCode(email, purpose);
  if (!code) return res.status(404).json({ error: 'No OTP found — request a new one first' });
  res.json({ code });
});

module.exports = router;
